name: workflow

on:
  push:
    branches:  [ main ]

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        architecture: 'x64'
        
    - name: Install pylint
      run: |
        pip install pylint
        
    - name: Create pylintrc file
      run: |
        pylint --generate-rcfile > .pylintrc
        
    - name: Linter test
      run: |
        pylint --disable=all $(git ls-files '*.py')
    
    - name: Docker build
      run: |
        docker build -t complete_app .
    - name: Docker login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_NAME }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Docker tag
      run: |
        docker tag complete_app razi202/continuous_learning:latest

    - name: Docker push
      run: |
        docker push razi202/continuous_learning:latest
